// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: onnx-data.proto3
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Onnx
{

    [global::ProtoBuf.ProtoContract()]
    public partial class SequenceProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"elem_type")]
        public int ElemType { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"tensor_values")]
        public global::System.Collections.Generic.List<TensorProto> TensorValues { get; } = new global::System.Collections.Generic.List<TensorProto>();

        [global::ProtoBuf.ProtoMember(4, Name = @"sparse_tensor_values")]
        public global::System.Collections.Generic.List<SparseTensorProto> SparseTensorValues { get; } = new global::System.Collections.Generic.List<SparseTensorProto>();

        [global::ProtoBuf.ProtoMember(5, Name = @"sequence_values")]
        public global::System.Collections.Generic.List<SequenceProto> SequenceValues { get; } = new global::System.Collections.Generic.List<SequenceProto>();

        [global::ProtoBuf.ProtoMember(6, Name = @"map_values")]
        public global::System.Collections.Generic.List<MapProto> MapValues { get; } = new global::System.Collections.Generic.List<MapProto>();

        [global::ProtoBuf.ProtoContract()]
        public enum DataType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"UNDEFINED")]
            Undefined = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"TENSOR")]
            Tensor = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"SPARSE_TENSOR")]
            SparseTensor = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"SEQUENCE")]
            Sequence = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"MAP")]
            Map = 4,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class MapProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"key_type")]
        public int KeyType { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"keys", IsPacked = true)]
        public long[] Keys { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"string_keys")]
        public global::System.Collections.Generic.List<byte[]> StringKeys { get; } = new global::System.Collections.Generic.List<byte[]>();

        [global::ProtoBuf.ProtoMember(5, Name = @"values")]
        public SequenceProto Values { get; set; }

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
