// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: onnx-operators-ml.proto3
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Onnx
{

    [global::ProtoBuf.ProtoContract()]
    public partial class FunctionProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"since_version")]
        public long SinceVersion { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"status")]
        public OperatorStatus Status { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"input")]
        public global::System.Collections.Generic.List<string> Inputs { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(5, Name = @"output")]
        public global::System.Collections.Generic.List<string> Outputs { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(6, Name = @"attribute")]
        public global::System.Collections.Generic.List<string> Attributes { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(7, Name = @"node")]
        public global::System.Collections.Generic.List<NodeProto> Nodes { get; } = new global::System.Collections.Generic.List<NodeProto>();

        [global::ProtoBuf.ProtoMember(8, Name = @"doc_string")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DocString { get; set; } = "";

        [global::ProtoBuf.ProtoMember(9, Name = @"opset_import")]
        public global::System.Collections.Generic.List<OperatorSetIdProto> OpsetImports { get; } = new global::System.Collections.Generic.List<OperatorSetIdProto>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class OperatorProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"op_type")]
        [global::System.ComponentModel.DefaultValue("")]
        public string OpType { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"since_version")]
        public long SinceVersion { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"status")]
        public OperatorStatus Status { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"doc_string")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DocString { get; set; } = "";

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class OperatorSetProto : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"magic")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Magic { get; set; } = "";

        [global::ProtoBuf.ProtoMember(2, Name = @"ir_version")]
        public long IrVersion { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"ir_version_prerelease")]
        [global::System.ComponentModel.DefaultValue("")]
        public string IrVersionPrerelease { get; set; } = "";

        [global::ProtoBuf.ProtoMember(7, Name = @"ir_build_metadata")]
        [global::System.ComponentModel.DefaultValue("")]
        public string IrBuildMetadata { get; set; } = "";

        [global::ProtoBuf.ProtoMember(4, Name = @"domain")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Domain { get; set; } = "";

        [global::ProtoBuf.ProtoMember(5, Name = @"opset_version")]
        public long OpsetVersion { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"doc_string")]
        [global::System.ComponentModel.DefaultValue("")]
        public string DocString { get; set; } = "";

        [global::ProtoBuf.ProtoMember(8, Name = @"operator")]
        public global::System.Collections.Generic.List<OperatorProto> Operators { get; } = new global::System.Collections.Generic.List<OperatorProto>();

        [global::ProtoBuf.ProtoMember(9, Name = @"functions")]
        public global::System.Collections.Generic.List<FunctionProto> Functions { get; } = new global::System.Collections.Generic.List<FunctionProto>();

    }

    [global::ProtoBuf.ProtoContract()]
    public enum OperatorStatus
    {
        [global::ProtoBuf.ProtoEnum(Name = @"EXPERIMENTAL")]
        Experimental = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"STABLE")]
        Stable = 1,
    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
